src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/AuthorsController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using TatBlog.Core.DTO;
using TatBlog.Core.Entities;
using TatBlog.Services.Blogs;
using TatBlog.Services.Media;
using TatBlog.WebApp.Areas.Admin.Models;

namespace TatBlog.WebApp.Areas.Admin.Controllers;

public class AuthorsController : Controller
{
    private readonly ILogger<PostsController> _logger;
    private readonly IAuthorRepository _authorRepository;
    private readonly IMediaManager _mediaManager;
    private readonly IMapper _mapper;
    private readonly IValidator<AuthorEditModel> _authorValidator;

    public AuthorsController(IAuthorRepository authorRepository, IMapper mapper, IMediaManager mediaManager, ILogger<PostsController> logger, IValidator<AuthorEditModel> authorValidator)
    {
        _authorRepository = authorRepository;
        _mapper = mapper;
        _mediaManager = mediaManager;
        _logger = logger;
        _authorValidator = authorValidator;
    }

    public async Task<IActionResult> Index(AuthorFilterModel model, [FromQuery(Name = "p")] int pageNumber = 1, [FromQuery(Name = "ps")] int pageSize = 10)
    {
        var authorQuery = _mapper.Map<AuthorQuery>(model);


        ViewData["AuthorsList"] = await _authorRepository.GetAuthorByQueryAsync(authorQuery, pageNumber, pageSize);
        ViewData["PagerQuery"] = new PagerQuery
        {
            Area = "Admin",
            Controller = "Authors",
            Action = "Index",
        };

        return View(model);
    }

    [HttpGet]
    public async Task<ActionResult> Edit(int id = 0)
    {
        var author = id > 0 ? await _authorRepository.GetAuthorByIdAsync(id) : null;

        var model = author == null ? new AuthorEditModel() : _mapper.Map<AuthorEditModel>(author);

        return View(model);
    }

    [HttpPost]
    public async Task<ActionResult> Edit(AuthorEditModel model)
    {
        var validator = HttpContext.RequestServices.GetService(typeof(IValidator<AuthorEditModel>));
        var validationResult = await _authorValidator.ValidateAsync(model);

        if (!validationResult.IsValid)
        {
            validationResult.AddToModelState(ModelState);
        }

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var author = model.Id > 0 ? await _authorRepository.GetAuthorByIdAsync(model.Id) : null;

        if (author == null)
        {
            author = _mapper.Map<Author>(model);

            author.Id = 0;
        }
        else
        {
            _mapper.Map(model, author);
        }

        if (model.ImageFile?.Length > 0)
        {
            var newImagePath = await _mediaManager.SaveFileAsync(model.ImageFile.OpenReadStream(), model.ImageFile.FileName, model.ImageFile.ContentType);

            if (!string.IsNullOrWhiteSpace(newImagePath))
            {
                await _mediaManager.DeleteFileAsync(author.ImageUrl);
                author.ImageUrl = newImagePath;
            }
        }

        await _authorRepository.AddOrUpdateAuthorAsync(author);

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<ActionResult> VerifyAuthorSlug(int id, string urlSlug)
    {
        var slugExisted = await _authorRepository.CheckAuthorSlugExisted(id, urlSlug);

        return slugExisted ? Json($"Slug '{urlSlug}' đã được sử dụng") : Json(true);
    }

    [HttpPost]
    public async Task<ActionResult> DeleteAuthor(string id)
    {
        await _authorRepository.DeleteAuthorByIdAsync(Convert.ToInt32(id));

        return RedirectToAction(nameof(Index));
    }
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/CategoriesController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using TatBlog.Core.DTO;
using TatBlog.Core.Entities;
using TatBlog.Services.Blogs;
using TatBlog.WebApp.Areas.Admin.Models;

namespace TatBlog.WebApp.Areas.Admin.Controllers;

public class CategoriesController : Controller
{
    private readonly ILogger<PostsController> _logger;
    private readonly ICategoryRepository _categoryRepository;
    private readonly IMapper _mapper;
    private readonly IValidator<CategoryEditModel> _categoryValidator;

    public CategoriesController(ILogger<PostsController> logger, ICategoryRepository categoryRepository, IMapper mapper, IValidator<CategoryEditModel> categoryValidator)
    {
        _logger = logger;
        _categoryRepository = categoryRepository;
        _mapper = mapper;
        _categoryValidator = categoryValidator;
    }

    public async Task<IActionResult> Index(CategoryFilterModel model,
                                          [FromQuery(Name = "p")] int pageNumber = 1,
                                          [FromQuery(Name = "ps")] int pageSize = 10)
    {
        var categoryQuery = _mapper.Map<CategoryQuery>(model);

        ViewData["CategoriesList"] = await _categoryRepository.GetCategoryByQueryAsync(categoryQuery, pageNumber, pageSize);

        ViewData["PagerQuery"] = new PagerQuery
        {
            Area = "Admin",
            Controller = "Categories",
            Action = "Index",
        };

        return View(model);
    }

    [HttpGet]
    public async Task<ActionResult> Edit(int id = 0)
    {
        var category = id > 0 ? await _categoryRepository.GetCategoryByIdAsync(id) : null;

        var model = category == null ? new CategoryEditModel() : _mapper.Map<CategoryEditModel>(category);

        return View(model);
    }

    [HttpPost]
    public async Task<ActionResult> Edit(CategoryEditModel model)
    {
        var validator = HttpContext.RequestServices.GetService(typeof(IValidator<CategoryEditModel>));
        var validationResult = await _categoryValidator.ValidateAsync(model);

        if (!validationResult.IsValid)
        {
            validationResult.AddToModelState(ModelState);
        }

        if (!ModelState.IsValid)
            return View(model);

        var category = model.Id > 0 ? await _categoryRepository.GetCategoryByIdAsync(model.Id) : null;

        if (category == null)
        {
            category = _mapper.Map<Category>(model);

            category.Id = 0;
        }
        else
        {
            _mapper.Map(model, category);
        }

        await _categoryRepository.AddOrUpdateCategoryAsync(category);

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<ActionResult> VerifyCategorySlug(int id, string urlSlug)
    {
        var slugExisted = await _categoryRepository.CheckCategorySlugExisted(id, urlSlug);

        return slugExisted ? Json($"Slug '{urlSlug}' đã được sử dụng") : Json(true);
    }

    [HttpPost]
    public async Task<ActionResult> ShowedChanged(string categoryId)
    {
        await _categoryRepository.ChangeCategoryStatusAsync(Convert.ToInt32(categoryId));

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<ActionResult> DeleteCategory(string id)
    {
        await _categoryRepository.DeleteCategoryByIdAsync(Convert.ToInt32(id));

        return RedirectToAction(nameof(Index));
    }
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/PostsController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TatBlog.Core.DTO;
using TatBlog.Core.Entities;
using TatBlog.Services.Blogs;
using TatBlog.Services.Media;
using TatBlog.WebApp.Areas.Admin.Models;

namespace TatBlog.WebApp.Areas.Admin.Controllers;

public class PostsController : Controller
{
    private readonly ILogger<PostsController> _logger;
    private readonly IBlogRepository _blogRepository;
    private readonly IAuthorRepository _authorRepository;
    private readonly ICategoryRepository _categoryRepository;
    private readonly IMediaManager _mediaManager;
    private readonly IMapper _mapper;
    private readonly IValidator<PostEditModel> _postValidator;

    public PostsController(IBlogRepository blogRepository, IMapper mapper, IMediaManager mediaManager, ILogger<PostsController> logger, IAuthorRepository authorRepository, ICategoryRepository categoryRepository, IValidator<PostEditModel> postValidator)
    {
        _blogRepository = blogRepository;
        _mapper = mapper;
        _mediaManager = mediaManager;
        _logger = logger;
        _authorRepository = authorRepository;
        _categoryRepository = categoryRepository;
        _postValidator = postValidator;
    }

    public async Task<IActionResult> Index(PostFilterModel model, [FromQuery(Name = "p")] int pageNumber = 1, [FromQuery(Name = "ps")] int pageSize = 10)
    {
        var postQuery = _mapper.Map<PostQuery>(model);

        ViewData["PostsList"] = await _blogRepository.GetPostByQueryAsync(postQuery, pageNumber, pageSize);
        ViewData["PagerQuery"] = new PagerQuery
        {
            Area = "Admin",
            Controller = "Posts",
            Action = "Index",
        };

        await PopulatePostFilterModelAsync(model);

        return View(model);
    }

    private async Task PopulatePostFilterModelAsync(PostFilterModel model)
    {
        var authors = await _authorRepository.GetAuthorsAsync();
        var categories = await _categoryRepository.GetCategoriesAsync();

        model.AuthorList = authors.Select(a => new SelectListItem
        {
            Text = a.FullName,
            Value = a.Id.ToString()
        });

        model.CategoryList = categories.Select(c => new SelectListItem
        {
            Text = c.Name,
            Value = c.Id.ToString()
        });
    }

    [HttpGet]
    public async Task<ActionResult> Edit(int id = 0)
    {
        // ID = 0 -> Thêm bài viết mới
        // ID > 0 : Đọc dữ liệu của bài viết từ CSDL
        var post = id > 0 ? await _blogRepository.GetPostByIdAsync(id, true) : null;

        // Tạo view model từ dữ liệu của bài viết
        var model = post == null ? new PostEditModel() : _mapper.Map<PostEditModel>(post);

        // Gán các giá trị khác nhau cho view model
        await PopulatePostEditModelAsync(model);

        return View(model);
    }

    private async Task PopulatePostEditModelAsync(PostEditModel model)
    {
        var authors = await _authorRepository.GetAuthorsAsync();
        var categories = await _categoryRepository.GetCategoriesAsync();

        model.AuthorList = authors.Select(a => new SelectListItem
        {
            Text = a.FullName,
            Value = a.Id.ToString()
        });

        model.CategoryList = categories.Select(c => new SelectListItem
        {
            Text = c.Name,
            Value = c.Id.ToString()
        });
    }

    [HttpPost]
    public async Task<ActionResult> Edit(PostEditModel model)
    {
        var postValidator = HttpContext.RequestServices.GetService(typeof(IValidator<PostEditModel>));
        var validationResult = await _postValidator.ValidateAsync(model);

        if (!validationResult.IsValid)
        {
            validationResult.AddToModelState(ModelState);
        }

        if (!ModelState.IsValid)
        {
            await PopulatePostEditModelAsync(model);
            return View(model);
        }

        var post = model.Id > 0 ? await _blogRepository.GetPostByIdAsync(model.Id) : null;

        if (post == null)
        {
            post = _mapper.Map<Post>(model);

            post.Id = 0;
            post.PostedDate = DateTime.Now;
        }
        else
        {
            _mapper.Map(model, post);

            post.Category = null;
            post.ModifiedDate = DateTime.Now;
        }

        if (model.ImageFile?.Length > 0)
        {
            var newImagePath = await _mediaManager.SaveFileAsync(model.ImageFile.OpenReadStream(), model.ImageFile.FileName, model.ImageFile.ContentType);

            if (!string.IsNullOrWhiteSpace(newImagePath))
            {
                await _mediaManager.DeleteFileAsync(post.ImageUrl);
                post.ImageUrl = newImagePath;
            }
        }

        await _blogRepository.AddOrUpdatePostAsync(post, model.GetSelectedTags());

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<ActionResult> VerifyPostSlug(int id, string urlSlug)
    {
        var slugExisted = await _blogRepository.IsPostSlugExistedAsync(id, urlSlug);

        return slugExisted ? Json($"Slug '{urlSlug}' đã được sử dụng") : Json(true);
    }

    [HttpPost]
    public async Task<ActionResult> PublishChanged(string postId)
    {
        await _blogRepository.ChangePostStatusAsync(Convert.ToInt32(postId));

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<ActionResult> DeletePost(string id)
    {
        await _blogRepository.DeletePostByIdAsync(Convert.ToInt32(id));

        return RedirectToAction(nameof(Index));
    }
}

src/TipsAndTricks/TatBlog.WebApp/Controllers/NewsLetterController.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using TatBlog.Services.Blogs;

namespace TatBlog.WebApp.Controllers;

public class NewsLetterController : Controller
{
    private readonly ISubscriberRepository _subscriberRepository;

    public NewsLetterController(ISubscriberRepository subscriberRepository)
    {
        _subscriberRepository = subscriberRepository;
    }

    public async Task<IActionResult> Subscribe(string email)
    {
        var subscription = await _subscriberRepository.SubscribeAsync(email);
        if (!subscription)
            return Content("Đã xảy ra lỗi khi đăng ký với email!");

        return Redirect(Request.Headers["Referer"].ToString());
    }

    public async Task<IActionResult> Unsubscribe(string email)
    {
        await _subscriberRepository.UnsubscribeAsync(email, "Không có nhu cầu nữa", true);

        return RedirectToAction("Index", "Blog");
    }
}

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/About.cshtml
@{
    ViewData["PageTitle"] = "Giới thiệu";
}

<h1>
    Đây là trang giới thiệu
</h1>

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/Archives.cshtml
@model IPagedList<Post>

@{
    ViewData["Title"] = "Danh sách bài viết";

    var postQuery = (ViewData["PostQuery"] as PostQuery) ?? new PostQuery();
}

<div class="p-4">
    <h3 class="text-primary mb-3">
        Những bài viết trong tháng @postQuery.Month năm @postQuery.Year
    </h3>

    @foreach (var postItem in Model)
    {
        <partial name="_PostItem" model="postItem" />
    }

    <partial name="_Pager" model="@Model" />
</div>

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/Author.cshtml
@model IPagedList<Post>

@{
    ViewData["Title"] = "Tác giả";

    var author = new Author();
    if (Model != null && Model.Count > 0)
        author = (Model[0].Author as Author);
}

<div class="p-4">
    @if (!string.IsNullOrWhiteSpace(author.FullName))
    {
        <h3 class="text-primary mb-3">
            Những bài viết thuộc tác giả '@author.FullName'
        </h3>
    }

    @foreach (var postItem in Model)
    {
        <partial name="_PostItem" model="postItem" />
    }

    <partial name="_Pager" model="@Model" />
</div>

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/Category.cshtml
@model IPagedList<Post>

@{
    ViewData["Title"] = "Chủ đề";

    var category = new Category();
    if (Model != null && Model.Count > 0)
        category = (Model[0].Category as Category);
}

<div class="p-4">
    @if (!string.IsNullOrWhiteSpace(category.Name))
    {
        <h3 class="text-primary mb-3">
            Những bài viết thuộc chủ đề '@category.Name'
        </h3>
    }

    @foreach (var postItem in Model)
    {
        <partial name="_PostItem" model="postItem" />
    }

    <partial name="_Pager" model="@Model" />
</div>

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/Contact.cshtml
@{
    ViewData["PageTitle"] = "Liên hệ";
}

<h1>
    Đây là trang liên hệ
</h1>

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/Index.cshtml
@model IPagedList<Post>

@{
    ViewData["Title"] = "Trang chủ";
    var postQuery = (ViewData["PostQuery"] as PostQuery) ?? new PostQuery();
}

@await Component.InvokeAsync("BestAuthors")

<hr>

<div class="p-4">
    @if (!string.IsNullOrWhiteSpace(postQuery.Keyword))
    {
        <h3 class="text-primary mb-3">
            Những bài viết với từ khoá '@postQuery.Keyword'
        </h3>
    }
    else
    {
        <h3 class="text-success mb-3">
            Danh sách bài viết
        </h3>
    }

    @foreach (var postItem in Model)
    {
        <partial name="_PostItem" model="postItem" />
    }

    <partial name="_Pager" model="@Model" />
</div>

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/Post.cshtml
@model Post

@{
    ViewData["Title"] = "Chi tiết bài viết";
    var imageUrl = string.IsNullOrWhiteSpace(Model.ImageUrl) ? "/images/loc.jpg" : $"/{Model.ImageUrl}";

    var comments = ViewData["Comments"] as IPagedList<Comment>;
}

<div class="text-danger">@Html.ValidationMessage("denied access")</div>

<div class="p-4 mb-5">
    <h1>Tiêu đề: @Model.Title</h1>
    <p>Ngày tạo: <i>@Html.DisplayFor(model => model.PostedDate)</i></p>
    <img src="@imageUrl" alt="@Model.Title" class="img-thumbnail">
    <hr>
    <p>
        <h5>
            Giới thiệu bài viết:
        </h5>
        @Html.Raw(Model.ShortDescription)
    </p>
    <p>
        <h5>
            Mô tả bài viết:
        </h5>
        @Html.Raw(Model.Description)
    </p>
    <h6>
        Lượt xem: <text class="text-primary">@Model.ViewCount</text>
    </h6>
    <h6>
        Tác giả: <text class="text-primary">@Model.Author.FullName</text>
    </h6>
    <h6>
        Chủ đề: <text class="text-primary">@Model.Category.Name</text>
    </h6>
    <figure>
        Thẻ:
        @foreach (var tag in Model.Tags)
        {
            <h6>
                <text class="text-primary">@tag.Name</text>
            </h6>
        }
    </figure>
</div>

<h2 class="row p-4 mb-3">
    <span class="col-sm-3 badge rounded-pill bg-black">Các bình luận</span>

    @foreach (var comment in comments)
    {
        <partial name="_CommentItem" model="comment" />
    }

    <partial name="_Pager" model="@comments" />
</h2>

<form method="post"
      enctype="multipart/form-data"
      class="row gy-2 gx-3 align-items-center"
      asp-area=""
      asp-controller="Blog"
      asp-action="Comment">
    <input type="hidden" name="postId" value="@Model.Id" />
    <h2 class="row mb-3">
        <span class="col-sm-3 badge rounded-pill bg-primary">Bình luận về bài viết</span>
    </h2>
    <div class="row mb-3">
        <label for="commentUsername" class="col-sm-2 col-form-label">Tên của bạn</label>
        <div class="col-sm-5">
            <input type="text" class="form-control" name="commentUsername" id="commentUsername" required>
        </div>
    </div>
    <div class="row mb-3">
        <label for="commentContent" class="col-sm-2 col-form-label">Nội dung</label>
        <div class="col-sm-10">
            <textarea class="form-control" style="max-height: 300px;" rows="100" id="commentContent" name="commentContent" required></textarea>
        </div>
    </div>
    <div class="row mb-3">
        <div class="d-block d-flex flex-row-reverse">
            <button type="submit" class="btn btn-primary w-25">
                Bình luận
            </button>
        </div>
    </div>
</form>

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/Tag.cshtml
@model IPagedList<Post>

@{
    ViewData["Title"] = "Thẻ bài viết";

    var tag = ViewData["Tag"] as Tag;
}

<div class="p-4">
    @if (tag != null)
    {
        <h3 class="text-primary mb-3">
            Những bài viết thuộc thẻ '@tag.Name'
        </h3>
    }

    @foreach (var postItem in Model)
    {
        <partial name="_PostItem" model="postItem" />
    }

    <partial name="_Pager" model="@Model" />
</div>

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/_CommentItem.cshtml
@model Comment

@{
    var imageUrl = "/images/loc.jpg";
}

<div class="row d-flex mt-3">
    <div class="col-md-8 col-lg-6">
        <div class="card shadow-0 border" style="background-color: #f0f2f5;">
            <div class="card-body p-4">
                <div class="card">
                    <div class="card-body">
                        <p>@Model.Content</p>
                        <div class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <img src="@imageUrl" alt="avatar" width="25"
                                     height="25" />
                                <p class="h4 mb-0 ms-2">@Model.UserName</p>
                            </div>
                            <div class="d-flex flex-row align-items-center">
                                <p class="h5 text-muted mb-0">@Model.PostDate</p>
                                <i class="far fa-thumbs-up mx-2 fa-xs text-black" style="margin-top: -0.16rem;"></i>
                                <p class="h5 text-muted mb-0">3</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/_NewsLetterForm.cshtml
<div class="mb-4">
    <h3 class="text-success mb-2">
        Đăng ký nhận thông báo khi có bài viết mới
    </h3>

    <div class="row">
        <section>
            <form method="post"
                  asp-area=""
                  asp-controller="NewsLetter"
                  asp-action="Subscribe">
                <div class="form-floating mb-3">
                    <input id="email" name="email" class="form-control" autocomplete="email" aria-required="true" placeholder="name@example.com" />
                    <label for="email" class="form-label">Email</label>
                </div>
                <button type="submit" class="btn btn-primary">Đăng ký</button>
            </form>
        </section>
    </div>
</div>

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/_Pager.cshtml
@model IPagedList<Post>

@{
    var postQuery = (ViewBag.PostQuery as PostQuery) ?? new PostQuery();
    var actionName = "Index";
    var slug = "";

    if (!string.IsNullOrWhiteSpace(postQuery.AuthorSlug))
    {
        actionName = "Author";
    }
    else if (!string.IsNullOrWhiteSpace(postQuery.CategorySlug))
    {
        actionName = "Category";
    }
    else if (!string.IsNullOrWhiteSpace(postQuery.TagSlug))
    {
        actionName = "Tag";
    }
}

@if (Model.PageCount > 1)
{
    <div class="text-center my-4">
        @if (Model.HasPreviousPage)
        {
            <a asp-controller="Blog"
               asp-action="@actionName"
               asp-route-slug="@slug"
               asp-route-k="@postQuery.Keyword"
               asp-route-p="@(Model.PageNumber - 1)"
               asp-route-ps="@Model.PageSize"
               class="btn btn-info">
                <i class="fa fa-arrow-left"></i>
                Trang trước
            </a>
        }
        else
        {
            <button type="button"
                    class="btn btn-outline-secondary"
                    disabled>
                <i class="fa fa-arrow-left"></i>
                Trang trước
            </button>
        }

        @if (Model.HasNextPage)
        {
            <a asp-controller="Blog"
               asp-action="@actionName"
               asp-route-slug="@slug"
               asp-route-k="@postQuery.Keyword"
               asp-route-p="@(Model.PageNumber + 1)"
               asp-route-ps="@Model.PageSize"
               class="btn btn-info">
                Trang sau
                <i class="fa fa-arrow-right"></i>
            </a>
        }
        else
        {
            <button type="button"
                    class="btn btn-outline-secondary"
                    disabled>
                Trang sau
                <i class="fa fa-arrow-right"></i>     
            </button>
        }
    </div>
}

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/_PostItem.cshtml
@model Post

@{
    var imageUrl = string.IsNullOrWhiteSpace(Model.ImageUrl) ? "/images/loc.jpg" : $"/{Model.ImageUrl}";
    var pagerQuery = (ViewData["PagerQuery"] as PagerQuery) ?? new PagerQuery();
}

<article class="blog-entry mb-4">
    <div class="card">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="@imageUrl" alt="@Model.Title" class="card-img">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">
                        <a title="@Model.Title"
                           style="text-decoration: none;"
                           asp-controller="@pagerQuery.Controller"
                           asp-action="Post"
                           asp-route-year="@Model.PostedDate.Year"
                           asp-route-month="@Model.PostedDate.Month"
                           asp-route-day="@Model.PostedDate.Day"
                           asp-route-slug="@Model.UrlSlug">
                            @Model.Title
                        </a>
                    </h5>
                    <p class="card-text">
                        <small class="text-muted">
                            Tác giả:
                        </small>
                        <span class="text-primary">
                            <a title="@Model.Author.FullName"
                               style="text-decoration: none;"
                               asp-controller="@pagerQuery.Controller"
                               asp-action="Author"
                               asp-route-slug="@Model.Author.UrlSlug">
                                @Model.Author.FullName
                            </a>
                        </span>
                        <small class="text-muted">
                            Chủ đề:
                        </small>
                        <span class="text-primary">
                            <a title="@Model.Category.Name"
                               style="text-decoration: none;"
                               asp-controller="@pagerQuery.Controller"
                               asp-action="Category"
                               asp-route-slug="@Model.Category.UrlSlug">
                                @Model.Category.Name
                            </a>
                        </span>
                    </p>
                    <p class="card-text">
                        @Html.Raw(Model.ShortDescription)
                    </p>
                    <div class="tag-list">
                        <partial name="_TagList" model="@Model.Tags" />
                    </div>
                    <div class="text-end">
                        <a class="btn btn-primary"
                           title="@Model.Title"
                           asp-controller="@pagerQuery.Controller"
                           asp-action="Post"
                           asp-route-year="@Model.PostedDate.Year"
                           asp-route-month="@Model.PostedDate.Month"
                           asp-route-day="@Model.PostedDate.Day"
                           asp-route-slug="@Model.UrlSlug">
                            Xem chi tiết
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>

src/TipsAndTricks/TatBlog.WebApp/Views/Blog/_TagList.cshtml
@model IList<Tag>

@foreach (var item in Model)
{
    <a class="btn btn-sm btn-outline-secondary"
       title="Tag: @item.Name"
       asp-controller="Blog"
       asp-action="Tag"
       asp-route-slug="@item.UrlSlug">
        @item.Name
    </a>
}